apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsign-issuer
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca-cert
spec:
  commonName: SelfSignedCommonName
  isCA: true
  issuerRef:
    kind: Issuer
    name: selfsign-issuer
  secretName: selfsigned-ca-cert
  subject:
    organizations:
      - SelfSignedOrg