---
clusterName: "es-beta"
nodeGroup: "master"

# The service that non master groups will try to connect to when joining the cluster
# This should be set to clusterName + "-" + nodeGroup for your master group
masterService: ""

# Elasticsearch roles that will be applied to this nodeGroup
# These will be set as environment variables. E.g. node.roles=master
# https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#node-roles
roles:
  - master
  - data
  - data_content
  - data_hot
  - data_warm
  - data_cold
  - ingest
  - ml
  - remote_cluster_client
  - transform

replicas: 3
minimumMasterNodes: 2

esMajorVersion: ""

# Allows you to add any config files in /usr/share/elasticsearch/config/
# such as elasticsearch.yml and log4j2.properties
esConfig:
  elasticsearch.yml: |
    xpack.license.self_generated.type: basic
    xpack.monitoring.collection.enabled: true
#esConfig: {}
#  elasticsearch.yml: |
#    key:
#      nestedkey: value
#  log4j2.properties: |
#    key = value

esJvmOptions:
  processors.options: |
    -XX:ActiveProcessorCount=2

# Disable it to use your own elastic-credential Secret.
secret:
  enabled: true
  password: "changemeonce" # generated randomly if not defined


imagePullSecrets:
  - name: "uvdockerrepo-secret"

esJavaOpts: "-Xms2g -Xmx2g -XX:MaxDirectMemorySize=2g"

resources:
  requests:
    cpu: "1500m"
    memory: "3Gi"
  limits:
    cpu: "1700m"
    memory: "3Gi"

initResources: {}
# limits:
#   cpu: "25m"
#   # memory: "128Mi"
# requests:
#   cpu: "25m"
#   memory: "128Mi"


volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3

extraVolumes:
  - name: elastic-hunspell
    emptyDir: {}
  - name: elastic-synonyms
    emptyDir: {}
# - name: extras
#   emptyDir: {}

extraVolumeMounts:
  - name: elastic-hunspell
    mountPath: /usr/share/elasticsearch/config/hunspell
    readOnly: false
  - name: elastic-synonyms
    mountPath: /usr/share/elasticsearch/config/synonyms
    readOnly: false
# - name: extras
#   mountPath: /usr/share/extras
#   readOnly: true

#extraInitContainers: []
extraInitContainers:
  - name: elasticsearch-custom-config-init
    image: "uvdeployment/videosearch:search_es_v0.0.2"
    imagePullPolicy: "IfNotPresent"
    volumeMounts:
      - name:  elastic-hunspell
        mountPath: /tmp/hunspell
      - name:  elastic-synonyms
        mountPath: /tmp/synonyms
    command:
      - bash
      - -c
      - |
        cp -rf /usr/src/app/hunspell/*  /tmp/hunspell
        cp -rf /usr/src/app/synonyms/*  /tmp/synonyms
# - name: do-something
#   image: busybox
#   command: ['do', 'something']

protocol: http
httpPort: 9200
transportPort: 9300

service:
  enabled: true
  type: NodePort
  # Consider that all endpoints are considered "ready" even if the Pods themselves are not
  # https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceSpec
  publishNotReadyAddresses: false
  nodePort: "30013"

# This is the max unavailable setting for the pod disruption budget
# The default value of 1 will make sure that kubernetes won't allow more than 1
# of your pods to be unavailable during maintenance
maxUnavailable: 1

nodeSelector: 
  node-class: es-beta